name: CI
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache the npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-mykey-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-mykey-
      - name: Use nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format:check
      - run: CI=true npm run test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage
      #For push requests
      - name: Build projekt
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - name: Create a Release 
        if: github.event_name == 'push' && github.ref == 'reft/heads/main'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: Latest release 

      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain arifoo.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}
